server:
  port: 8080
  verbose: true
  webhook_host: "127.0.0.1"
  webhook_port: 4407

standalone_mode: false

store:
  vkn: "1234567890"
  name: "Demo Mağazası"
  address: "Örnek Mahalle, Kadıköy/İstanbul"

revenue_authority:
  url: "http://127.0.0.1:4406"

receipt_bank:
  url: "http://127.0.0.1:4403"

kisim:
  - id: 1
    name: "Temel Gıda"
    tax_rate: 10
    preset_price: 5.50
  - id: 2
    name: "Yemek"
    tax_rate: 20
    preset_price: 12.75
